# Repeat standard config options
baseurl: "https://hackshackers.com/"
enableEmoji: true
ignoreFiles: [ "README\\.md$", "example-group.yml$" ]
languageCode: "en-us"
title: "Hacks/Hackers"
theme: "hackshackers-2017"
disableKinds: ["RSS", "sitemap"]

# Dev-specific config options
# Revert for production use
contentDir: "content"
dataDir: "content/data"

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"

menu:
  main:
    - Name: About
      URL: "/about/"
    - Name: Find A Group
      URL: "/groups/"
    # - Name: Events
    #   URL: "/featured-events/"
    - Name: Resources
      URL: "/resources/"
    - Name: Blog
      URL: "/blog/"
    - Name: Hack This Site
      URL: "/hack-this-site/"

params:
  twitter: HacksHackers
  facebook: HacksHackers
  tagline: join the media revolution
  subtagline: rebooting journalism
  og_image:
    url: "https://hackshackers.com/images/hh_logo_stacked.jpg"
    width: 920
    height: 365
  og_desc: Hacks/Hackers is creating a network of journalists and technologists who rethink the future of news and information.
  events:
    homepage: 6
