baseurl = "https://hackshackers.com/"
enableEmoji = true
ignoreFiles = [ "README\\.md$" ]
languageCode = "en-us"
title = "Hacks/Hackers"
theme = "hackshackers-2017"

[params]
	staticDir = "/themes/hackshackers-2017/static"